### ISSUE TITLE
Submit data for Nivelles

### ISSUE THREAD

**Issue by drupol** [EqualStreetNames/equalstreetnames#142]
Hello,

I just created the data for Nivelles(https://github.com/drupol/equalstreetnames-nivelles), what is the procedure to submit a new city into this repo?

Thanks!

**Comment by jbelien** [comment]
Awesome news @drupol ! 🎉 

I see 2 options:

1. You want to keep full control over the data repository, its updates, and the website that displays the map of Nivelles ; if so, you can just submit a PR to add a sub-module pointing to your repository in the `cities` folder (like we did for the cities outside Belgium) ;
2. You want us to take care of the (automated) updates and the hosting of the website for Nivelles ; if so, I'll create a new repository for Nivelles in our Open Knowledge Belgium organization and you will be able to send a PR with your changes to that repository ;

Let me know which option you would prefer.

**Comment by drupol** [comment]
Option 2 please :)

**Comment by jbelien** [comment]
Done!
The sub-module for Nivelles is ready: https://github.com/openknowledgebe/equalstreetnames/tree/master/cities

At the moment, there is only 1 street in Nivelles that has the Wikidata reference: "Avenue Reine Astrid"
You can see the list here: https://github.com/openknowledgebe/equalstreetnames-nivelles/blob/master/data/gender.csv

Since there is only 1 street, I won't deploy the website yet but I'll add the automated data update process so if you update the OpenStreetMap data it will automatically update our repository.

**Comment by drupol** [comment]
This is great, thanks !!!

**Comment by jbelien** [comment]
Haha, thanks @RobinLinde !
I'll deploy `https://nivelles.openstreetmap.be/` later today, I'll let you know when you can enable the redirection. 👍 

WHAT A TEAM ! \o/

**Comment by jbelien** [comment]
@drupol Data and website will be automatically updated once a week.

**Comment by drupol** [comment]
So, the marker on the map(https://equalstreetnames.be/) will appear soon?

**Comment by RobinLinde** [comment]
@jbelien Redirect should work now, also added link to equalstreetnames.eu (https://github.com/RobinLinde/EqualStreetNamesLanding/pull/1)
