### ISSUE TITLE
Incorrect birth/ death day parsing

### ISSUE THREAD

**Issue by zorae** [EqualStreetNames/equalstreetnames#159]
For streets named after Virgin Mary, the birth and death dates from her [Wikidata entry](https://www.wikidata.org/wiki/Q345) get incorrectly parsed. The website displays her lifespan as "100-100".

See "Marienplatz" street in [Freising](https://freising.equalstreetnames.eu/en/index.html#17.56/48.400906/11.744044)

**Comment by jbelien** [comment]
There is indeed an issue.

For the date of birth (`P569`), I get `-0100-00-00T00:00:00Z`.
For the date of death (`P570`), I get `+0100-00-00T00:00:00Z`.

I probably won't be able to convert that (easily) to "1. century BCE" and "1. century" but it should be "-100 - 100" instead of "100 - 100".

I'll try to fix that.
Thanks for the notice.

**Comment by jbelien** [comment]
Thanks a lot @zorae !
It's now fixed and will be applied to every website during next update (next Thursday for Freising).
