### ISSUE TITLE
Last Update failed

### ISSUE THREAD

**Issue by Sequynth** [EqualStreetNames/equalstreetnames#610]
Seems like the update and deploy action at the beginning of this month failed.

https://github.com/EqualStreetNames/equalstreetnames/actions

**Comment by jbelien** [comment]
Thank you for the notice @Sequynth!
There are indeed several issues.

- [Deploy global website](https://github.com/EqualStreetNames/equalstreetnames/actions/workflows/deploy-global.yml) was failing because of the missing boundaries in Assen, Netherlands ; this is fixed in https://github.com/EqualStreetNames/equalstreetnames-assen/commit/7fa6f581c1a585850105df3de86e2c96185078ef
- Each city specific website is failing (or at least some of them) are failing since I've moved website to sub-module ; I'll fix it ASAP

**Comment by jbelien** [comment]
- [x] https://github.com/EqualStreetNames/equalstreetnames-brussels/

**Comment by jbelien** [comment]
Everything should be working again.
Let me know if I missed a deploy process.
